language: java
jdk:
  - oraclejdk8
install:
  - mkdir -p /home/travis/wpilib/java/current/lib/
  - cp lib/WPILib.jar /home/travis/wpilib/java/current/lib/
  - cp lib/NetworkTables.jar /home/travis/wpilib/java/current/lib/
script:
  - ant test

